#################
#               #
#  S O U R C E  #
#               #
#################

/gate/source/addSource twogamma
/gate/source/twogamma/setActivity 500000. becquerel
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/setForcedUnstableFlag true
/gate/source/twogamma/setForcedHalfLife 6586.2 s
/gate/source/twogamma/setType backtoback
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 511. keV
/gate/source/twogamma/gps/type Volume
/gate/source/twogamma/gps/shape Cylinder
/gate/source/twogamma/gps/radius 15. mm
/gate/source/twogamma/gps/halfz 34.0 mm
/gate/source/twogamma/gps/centre 0.0 -20.0 0.0 mm
/gate/source/twogamma/gps/angtype iso

/gate/source/addSource twogamma2
/gate/source/twogamma2/setActivity 750000. becquerel
/gate/source/twogamma2/gps/particle gamma
/gate/source/twogamma2/setForcedUnstableFlag true
/gate/source/twogamma2/setForcedHalfLife 6586.2 s
/gate/source/twogamma2/setType backtoback
/gate/source/twogamma2/gps/energytype Mono
/gate/source/twogamma2/gps/monoenergy 511. keV
/gate/source/twogamma2/gps/type Volume
/gate/source/twogamma2/gps/shape Cylinder
/gate/source/twogamma2/gps/radius 8. mm
/gate/source/twogamma2/gps/halfz 30.0 mm
/gate/source/twogamma2/gps/centre 25. 25.0 0. mm
/gate/source/twogamma2/gps/angtype iso

/gate/source/addSource twogamma3
/gate/source/twogamma3/setActivity 250000. becquerel
/gate/source/twogamma3/gps/particle gamma
/gate/source/twogamma3/setForcedUnstableFlag true
/gate/source/twogamma3/setForcedHalfLife 6586.2 s
/gate/source/twogamma3/setType backtoback
/gate/source/twogamma3/gps/energytype Mono
/gate/source/twogamma3/gps/monoenergy 511. keV
/gate/source/twogamma3/gps/type Volume
/gate/source/twogamma3/gps/shape Cylinder
/gate/source/twogamma3/gps/radius 5. mm
/gate/source/twogamma3/gps/halfz 38.0 mm
/gate/source/twogamma3/gps/centre -25. 25.0 0. mm
/gate/source/twogamma3/gps/angtype iso

#/gate/source/addSource F18LineSource
#/gate/source/F18LineSource/setActivity 100000. becquerel
#/gate/source/F18LineSource/gps/particle e+
#/gate/source/F18LineSource/gps/energytype Fluor18
#/gate/source/F18LineSource/gps/centre 0.0 0.0 0.0 cm
#/gate/source/F18LineSource/gps/angtype iso

#/gate/source/addSource F18LineSource
#/gate/source/F18LineSource/setActivity 1000000. becquerel
#/gate/source/F18LineSource/gps/particle e+
#/gate/source/F18LineSource/setForcedUnstableFlag true
#/gate/source/F18LineSource/setForcedHalfLife 6586.2 s
#/gate/source/F18LineSource/gps/energytype Fluor18
#/gate/source/F18LineSource/gps/type Volume
#/gate/source/F18LineSource/gps/shape Cylinder
#/gate/source/F18LineSource/gps/radius .5 mm
#/gate/source/F18LineSource/gps/halfz 34.0 mm
#/gate/source/F18LineSource/gps/angtype iso
#/gate/source/F18LineSource/gps/centre 0. -20.0 0. mm

#/gate/source/addSource O15LineSource
#/gate/source/O15LineSource/setActivity 1000000. becquerel
#/gate/source/O15LineSource/gps/particle e+
#/gate/source/O15LineSource/setForcedUnstableFlag true
#/gate/source/O15LineSource/setForcedHalfLife 122.24 s
#/gate/source/O15LineSource/gps/energytype Oxygen15
#/gate/source/O15LineSource/gps/type Volume
#/gate/source/O15LineSource/gps/shape Cylinder
#/gate/source/O15LineSource/gps/radius .5 mm
#/gate/source/O15LineSource/gps/halfz 34.0 mm
#/gate/source/O15LineSource/gps/angtype iso
#/gate/source/O15LineSource/gps/centre 20. 20.0 0. mm

/gate/source/list

