#
#       P H Y S I C S
#

/gate/physics/addPhysicsList emstandard

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering 
/gate/physics/processes/RayleighScattering/setModel LivermoreModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation e+

/gate/physics/addProcess eMultipleScattering e-
/gate/physics/addProcess eMultipleScattering e+
#/gate/physics/addProcess eMultipleScattering
#/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
#/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/addProcess RadioactiveDecay

/gate/physics/addAtomDeexcitation
#/process/em/fluo  false
#/process/em/auger false
#/process/em/pixe  false

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
#       C U T S
#


# Cuts for particle in NEMACylinder
#/gate/physics/Gamma/SetCutInRegion      NEMACylinder 0.5 cm
#/gate/physics/Electron/SetCutInRegion   NEMACylinder 0.5 cm
#/gate/physics/Positron/SetCutInRegion   NEMACylinder 0.5 cm

# Cuts for particle in NEMACylinder
/gate/physics/Gamma/SetCutInRegion      LSO 0.5 cm
/gate/physics/Electron/SetCutInRegion   LSO 0.5 cm
/gate/physics/Positron/SetCutInRegion   LSO 0.5 cm
