## Voxelized XCAT source ##

/gate/source/addSource                                          xcatsource voxel
/gate/source/xcatsource/reader/insert                           image
/gate/source/xcatsource/imageReader/translator/insert           range

## mCT_Act_heart.dat contains activities for every voxel
/gate/source/xcatsource/imageReader/rangeTranslator/readTable   tables/mCT_Act_heart.dat

## filename.h33: header for the activity image, in binary format (uint16)
/gate/source/xcatsource/imageReader/readFile                     data/mCT_xcat_static_m_act.h33
/gate/source/xcatsource/imageReader/verbose                      1

## backtoback ##
/gate/source/xcatsource/setType backtoback 
/gate/source/xcatsource/gps/particle gamma 
/gate/source/xcatsource/gps/energytype Mono  
/gate/source/xcatsource/gps/angtype iso 
/gate/source/xcatsource/setForcedHalfLife 122.24 s
/gate/source/xcatsource/setForcedUnstableFlag true
/gate/source/xcatsource/gps/monoenergy 511. keV 
## ion        ##
#/gate/source/xcatsource/gps/particle          ion
#/gate/source/xcatsource/gps/ion               8 15 0 0
#/gate/source/xcatsource/gps/energytype        Mono  
#/gate/source/xcatsource/gps/monoenergy        0. keV 
#/gate/source/xcatsource/setForcedUnstableFlag true
#/gate/source/xcatsource/useDefaultHalfLife
#/gate/source/xcatsource/gps/angtype iso 

## position the source in the middle
/gate/source/xcatsource/setPosition  -280. -117. -154. mm

#/gate/source/xcatsource/gps/mintheta 0. deg 
#/gate/source/xcatsource/gps/maxtheta 90. deg 
#/gate/source/xcatsource/gps/minphi 0. deg 
#/gate/source/xcatsource/gps/maxphi 360. deg 
#/gate/source/xcatsource/attachTo        Xcat
